# Generated by Django 3.0.6 on 2020-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], max_length=200, null=True),
        ),
    ]
