# Generated by Django 3.0.6 on 2020-05-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.CharField(max_length=160, null=True)),
                ('name', models.CharField(max_length=160, null=True)),
                ('text_media', models.CharField(max_length=200, null=True)),
                ('send_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
