# Generated by Django 3.0.6 on 2020-05-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200509_1026'),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='text_media',
        ),
        migrations.AddField(
            model_name='text',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
